# ===============================
# 🏠 MINI SWEET HOME - ZSH CONFIG
# ===============================

# Charger les configurations modulaires
source ~/mini-sweet-home/configs/shell/zsh/exports.zsh
source ~/mini-sweet-home/configs/shell/zsh/aliases.zsh
source ~/mini-sweet-home/configs/shell/zsh/functions.zsh
source ~/mini-sweet-home/configs/shell/zsh/prompt.zsh
