# ===============================
# ⚡ DOTFILES V4 - ZSH CONFIG
# ===============================

# Charger les configurations modulaires
source ~/dotfiles/configs/shell/zsh/exports.zsh
source ~/dotfiles/configs/shell/zsh/aliases.zsh
source ~/dotfiles/configs/shell/zsh/functions.zsh
source ~/dotfiles/configs/shell/zsh/prompt.zsh
