return {
	{
		"nvim-treesitter/nvim-treesitter",
		branch = "main",
		lazy = false,
		build = ":TSUpdate",
		main = "nvim-treesitter",
		dependencies = {
			{
				"nvim-treesitter/nvim-treesitter-textobjects",
				branch = "main",
				event = "VeryLazy",
			},
		},
		opts = {
			ensure_installed = {
				"c",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"elixir",
				"heex",
				"javascript",
				"typescript",
				"tsx",
				"jsx",
				"html",
				"markdown_inline",
				"markdown",
				"cpp",
				"rust",
				"typescript",
				"tmux",
				"dockerfile",
				"bash",
				"jsdoc",
				"json",
				"jsonc",
				"luadoc",
				"luap",
				"regex",
				"toml",
				"python",
				"php",
				"rust",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"sql",
				"sqlite",
				"templ",
				"tmpl",
				"gotmpl",
				"go",
				"gotexttmpl",
				"sql",
				"java",
				"kotlin",
				"prisma",
				"yml",
			},
			sync_install = false,
			highlight = { enable = true, additional_vim_regex_highlighting = false },
			indent = { enable = true },

			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-D>",
					node_incremental = "<C-D>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
			textobjects = {
				move = {
					enable = true,
					goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer" },
					goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer" },
					goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer" },
					goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer" },
				},
			},
		},
	},
}
